spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    datasource:
        url: jdbc:mysql://localhost:3306/bookdatabase
        username: root
        password: Mospwn13295X
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        database: h2
        console:
            enabled: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: nefaryan.devmail@gmail.com
        password: bqpclgkdxgnwsjwa
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    jackson:
        serialization:
            fail-on-empty-beans: false